### ISSUE TITLE
'undefined: cfr.NewVanilla' when go build

### ISSUE THREAD

**Issue by Stu-Yang** [timpalpant/go-cfr#3]
Hi, @timpalpant ~ Thanks for your the code of go-cfr. Now, I'm working on go-cfr and want to run the example of Kuhn Poker in [Usage](https://github.com/timpalpant/go-cfr#usage). However, there are some errors when I `go bulid` on Ubuntu. Here are details:

```shell
root@yp:~/yp_workplace# go version
go version go1.20 linux/amd64
root@yp:~/yp_workplace# git clone https://github.com/timpalpant/go-cfr
root@yp:~/yp_workplace# cd go-cfr
root@yp:~/yp_workplace/go-cfr# mkdir main
root@yp:~/yp_workplace/go-cfr# cd main
root@yp:~/yp_workplace/go-cfr/main# touch kuhn_poker.go
```
and add the following code (i.e., example of Kuhn Poker in [Usage](https://github.com/timpalpant/go-cfr#usage)) into `kuhn_poker.go`
```go
package main

import (
	"fmt"

	"github.com/timpalpant/go-cfr"
	"github.com/timpalpant/go-cfr/kuhn"
	"github.com/timpalpant/go-cfr/tree"
)

func main() {
	poker := kuhn.NewGame()
	vanillaCFR := cfr.NewVanilla()
	nIter := 10000
	expectedValue := 0.0
	for i := 1; i <= nIter; i++ {
		expectedValue += vanillaCFR.Run(poker)
	}

	expectedValue /= float64(nIter)
	fmt.Printf("Expected value is: %v\n", expectedValue)

	tree.VisitInfoSets(poker, func(player int, infoSet string) {
		strat := vanillaCFR.GetStrategy(player, infoSet)
		if strat != nil {
			fmt.Printf("[player %d] %6s: check=%.2f bet=%.2f\n",
				player, infoSet, strat[0], strat[1])
		}
	})
}
```
then run
```shell
root@yp:~/yp_workplace/go-cfr/main# go build kuhn_poker.go 
# command-line-arguments
./kuhn_poker.go:13:20: undefined: cfr.NewVanilla
./kuhn_poker.go:23:28: cannot use func(player int, infoSet string) {…} (value of type func(player int, infoSet string)) as func(player int, infoSet cfr.InfoSet) value in argument to tree.VisitInfoSets
```
I cann't find `cfr.NewVanilla` in go-cfr, and this has nothing to do with go. I would like to know how to solve this problem, or any idea. 

Looking forward to your reply.

**Comment by timpalpant** [comment]
Hi @Stu-Yang, as you've noticed, the README is not up-to-date with the latest API. I've updated it.

Unfortunately I do not work on this project any more and won't be able to support it. I'd recommend looking into https://github.com/deepmind/open_spiel which is a mature and well-supported toolkit from DeepMind that includes all of the algorithms available here.
